/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Currently active delegation status.
*/
export class ActiveSharedWalletAccountPublicKeysForEachCoSignersIsCollected1DelegationActive {
    'status': ActiveSharedWalletAccountPublicKeysForEachCoSignersIsCollected1DelegationActiveStatusEnum;
    /**
    * A unique Stake-Pool identifier (present only if status = `delegating`)
    */
    'target'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "ActiveSharedWalletAccountPublicKeysForEachCoSignersIsCollected1DelegationActiveStatusEnum",
            "format": ""
        },
        {
            "name": "target",
            "baseName": "target",
            "type": "string",
            "format": "hex|bech32"
        }    ];

    static getAttributeTypeMap() {
        return ActiveSharedWalletAccountPublicKeysForEachCoSignersIsCollected1DelegationActive.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ActiveSharedWalletAccountPublicKeysForEachCoSignersIsCollected1DelegationActiveStatusEnum = "not_delegating" | "delegating" ;

