/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ActiveSharedWalletAccountPublicKeysForEachCoSignersIsCollected1DelegationActive } from './ActiveSharedWalletAccountPublicKeysForEachCoSignersIsCollected1DelegationActive';
import { ActiveSharedWalletAccountPublicKeysForEachCoSignersIsCollected1DelegationNext } from './ActiveSharedWalletAccountPublicKeysForEachCoSignersIsCollected1DelegationNext';
import { HttpFile } from '../http/http';

/**
* Delegation settings
*/
export class ActiveSharedWalletAccountPublicKeysForEachCoSignersIsCollected1Delegation {
    'active': ActiveSharedWalletAccountPublicKeysForEachCoSignersIsCollected1DelegationActive;
    'next': Array<ActiveSharedWalletAccountPublicKeysForEachCoSignersIsCollected1DelegationNext>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "active",
            "baseName": "active",
            "type": "ActiveSharedWalletAccountPublicKeysForEachCoSignersIsCollected1DelegationActive",
            "format": ""
        },
        {
            "name": "next",
            "baseName": "next",
            "type": "Array<ActiveSharedWalletAccountPublicKeysForEachCoSignersIsCollected1DelegationNext>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ActiveSharedWalletAccountPublicKeysForEachCoSignersIsCollected1Delegation.attributeTypeMap;
    }

    public constructor() {
    }
}

