/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ScriptTemplateValue } from './ScriptTemplateValue';
import { HttpFile } from '../http/http';

export class Any {
    /**
    * Script primitive for which a signing key corresponding to any of the list cosigners' verification keys is expected to make the script valid. It is equivalent to `some` with `\"at_least\"=1`.
    */
    'any': Array<ScriptTemplateValue>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "any",
            "baseName": "any",
            "type": "Array<ScriptTemplateValue>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Any.attributeTypeMap;
    }

    public constructor() {
    }
}

