/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AnyScriptOneOf } from './AnyScriptOneOf';
import { DecodeTransaction202ResponseMintTokensInnerPolicyScriptOneOf1 } from './DecodeTransaction202ResponseMintTokensInnerPolicyScriptOneOf1';
import { ScriptValue } from './ScriptValue';
import { HttpFile } from '../http/http';

export class AnyScript {
    'scriptType': AnyScriptScriptTypeEnum;
    'script': string | any;
    'languageVersion': AnyScriptLanguageVersionEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "scriptType",
            "baseName": "script_type",
            "type": "AnyScriptScriptTypeEnum",
            "format": ""
        },
        {
            "name": "script",
            "baseName": "script",
            "type": "string | any",
            "format": ""
        },
        {
            "name": "languageVersion",
            "baseName": "language_version",
            "type": "AnyScriptLanguageVersionEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AnyScript.attributeTypeMap;
    }

    public constructor() {
    }
}


export type AnyScriptScriptTypeEnum = "plutus" ;
export type AnyScriptLanguageVersionEnum = "v1" | "v2" ;

