/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NativeAssetsMetadata } from './NativeAssetsMetadata';
import { HttpFile } from '../http/http';

export class ApiAsset {
    /**
    * A unique identifier of the asset's monetary policy. The policy controls how assets of this kind are created and destroyed.  The contents are the blake2b-224 hash of the monetary policy script, encoded in hexadecimal. 
    */
    'policyId': string;
    /**
    * The asset on-chain type which acts as a sub-identifier within a policy. Although we call it \"asset name\", the value needn't be text, and it could even be empty.  For policies with a single fungible asset item, asset name is typically an empty string.  This value can be up to 32 bytes of arbitrary data (which is 64 hexadecimal digits). 
    */
    'assetName': string;
    /**
    * A user-facing short fingerprint which combines the `policy_id` and `asset_name` to allow for an easier human comparison of assets. Note that it is generally **not okay** to use this fingerprint as a unique identifier for it is not collision resistant. Yet within the context of a single wallet, it makes for a (rather) short user-facing comparison mean. 
    */
    'fingerprint': string;
    'metadata'?: NativeAssetsMetadata;
    /**
    * If there was an error fetching metadata from the server, this will be set to one of `fetch` or `parse`, to indicate the kind of error. 
    */
    'metadataError'?: ApiAssetMetadataErrorEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "policyId",
            "baseName": "policy_id",
            "type": "string",
            "format": "hex"
        },
        {
            "name": "assetName",
            "baseName": "asset_name",
            "type": "string",
            "format": "hex"
        },
        {
            "name": "fingerprint",
            "baseName": "fingerprint",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "NativeAssetsMetadata",
            "format": ""
        },
        {
            "name": "metadataError",
            "baseName": "metadata_error",
            "type": "ApiAssetMetadataErrorEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiAsset.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ApiAssetMetadataErrorEnum = "fetch" | "parse" ;

