/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* patate
*/
export class ApiByronWalletRandomXPrvPostData {
    'style'?: ApiByronWalletRandomXPrvPostDataStyleEnum;
    'name': string;
    /**
    * A root private key, encrypted using a given passphrase. The underlying key should contain: - A private key - A chain code - A public key 
    */
    'encryptedRootPrivateKey': string;
    /**
    * A hash of master passphrase. The hash should be an output of a Scrypt function with the following parameters: - logN = 14 - r = 8 - p = 1 
    */
    'passphraseHash': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "style",
            "baseName": "style",
            "type": "ApiByronWalletRandomXPrvPostDataStyleEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "encryptedRootPrivateKey",
            "baseName": "encrypted_root_private_key",
            "type": "string",
            "format": "hex"
        },
        {
            "name": "passphraseHash",
            "baseName": "passphrase_hash",
            "type": "string",
            "format": "hex"
        }    ];

    static getAttributeTypeMap() {
        return ApiByronWalletRandomXPrvPostData.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ApiByronWalletRandomXPrvPostDataStyleEnum = "random" ;

