/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BalanceTransactionRequestInputsInner } from './BalanceTransactionRequestInputsInner';
import { BalanceTransactionRequestRedeemersInner } from './BalanceTransactionRequestRedeemersInner';
import { HttpFile } from '../http/http';

export class ApiBalanceTransactionPostData {
    /**
    * The CBOR-encoded transaction, represented in either hex or base64 encoding. This always includes the transaction body and the witness set, even if the latter is empty. 
    */
    'transaction': string;
    /**
    * A list of additional transaction inputs foreign to the wallet.
    */
    'inputs'?: Array<BalanceTransactionRequestInputsInner>;
    /**
    * A list of redeemers data with their purpose.
    */
    'redeemers'?: Array<BalanceTransactionRequestRedeemersInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "transaction",
            "baseName": "transaction",
            "type": "string",
            "format": "base64|base16"
        },
        {
            "name": "inputs",
            "baseName": "inputs",
            "type": "Array<BalanceTransactionRequestInputsInner>",
            "format": ""
        },
        {
            "name": "redeemers",
            "baseName": "redeemers",
            "type": "Array<BalanceTransactionRequestRedeemersInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiBalanceTransactionPostData.attributeTypeMap;
    }

    public constructor() {
    }
}

