/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ApiByronWalletIcarusPostData {
    'style'?: ApiByronWalletIcarusPostDataStyleEnum;
    'name': string;
    /**
    * A master passphrase to lock and protect the wallet for sensitive operation (e.g. sending funds)
    */
    'passphrase': string;
    /**
    * A list of mnemonic words
    */
    'mnemonicSentence': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "style",
            "baseName": "style",
            "type": "ApiByronWalletIcarusPostDataStyleEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "passphrase",
            "baseName": "passphrase",
            "type": "string",
            "format": ""
        },
        {
            "name": "mnemonicSentence",
            "baseName": "mnemonic_sentence",
            "type": "Array<string>",
            "format": "bip-0039-mnemonic-word{english}"
        }    ];

    static getAttributeTypeMap() {
        return ApiByronWalletIcarusPostData.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ApiByronWalletIcarusPostDataStyleEnum = "icarus" ;

