/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListByronWallets200ResponseInnerBalance } from './ListByronWallets200ResponseInnerBalance';
import { ListWallets200ResponseInnerAssets } from './ListWallets200ResponseInnerAssets';
import { ListWallets200ResponseInnerPassphrase } from './ListWallets200ResponseInnerPassphrase';
import { ListWallets200ResponseInnerState } from './ListWallets200ResponseInnerState';
import { ListWallets200ResponseInnerTip } from './ListWallets200ResponseInnerTip';
import { HttpFile } from '../http/http';

export class ApiByronWallet {
    /**
    * A unique identifier for the wallet
    */
    'id': string;
    'balance': ListByronWallets200ResponseInnerBalance;
    'assets': ListWallets200ResponseInnerAssets;
    /**
    * Mechanism used for discovering addresses.
    */
    'discovery': ApiByronWalletDiscoveryEnum;
    'name': string;
    'passphrase'?: ListWallets200ResponseInnerPassphrase;
    'state': ListWallets200ResponseInnerState;
    'tip': ListWallets200ResponseInnerTip;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "hex"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "ListByronWallets200ResponseInnerBalance",
            "format": ""
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "ListWallets200ResponseInnerAssets",
            "format": ""
        },
        {
            "name": "discovery",
            "baseName": "discovery",
            "type": "ApiByronWalletDiscoveryEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "passphrase",
            "baseName": "passphrase",
            "type": "ListWallets200ResponseInnerPassphrase",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "ListWallets200ResponseInnerState",
            "format": ""
        },
        {
            "name": "tip",
            "baseName": "tip",
            "type": "ListWallets200ResponseInnerTip",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiByronWallet.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ApiByronWalletDiscoveryEnum = "random" | "sequential" ;

