/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConstructTransaction202ResponseCoinSelection } from './ConstructTransaction202ResponseCoinSelection';
import { GetUTxOsStatistics200ResponseTotal } from './GetUTxOsStatistics200ResponseTotal';
import { HttpFile } from '../http/http';

export class ApiConstructTransaction {
    /**
    * The CBOR-encoded transaction, represented in base64 encoding. This always includes the transaction body and the witness set, even if the latter is empty. 
    */
    'transaction': string;
    'coinSelection': ConstructTransaction202ResponseCoinSelection;
    'fee': GetUTxOsStatistics200ResponseTotal;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "transaction",
            "baseName": "transaction",
            "type": "string",
            "format": "base64"
        },
        {
            "name": "coinSelection",
            "baseName": "coin_selection",
            "type": "ConstructTransaction202ResponseCoinSelection",
            "format": ""
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "GetUTxOsStatistics200ResponseTotal",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiConstructTransaction.attributeTypeMap;
    }

    public constructor() {
    }
}

