/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConstructTransaction202ResponseCoinSelectionCertificatesInner } from './ConstructTransaction202ResponseCoinSelectionCertificatesInner';
import { ConstructTransaction202ResponseCoinSelectionChangeInner } from './ConstructTransaction202ResponseCoinSelectionChangeInner';
import { ConstructTransaction202ResponseCoinSelectionCollateralInner } from './ConstructTransaction202ResponseCoinSelectionCollateralInner';
import { ConstructTransaction202ResponseCoinSelectionInputsInner } from './ConstructTransaction202ResponseCoinSelectionInputsInner';
import { ConstructTransaction202ResponseCoinSelectionWithdrawalsInner } from './ConstructTransaction202ResponseCoinSelectionWithdrawalsInner';
import { GetUTxOsStatistics200ResponseTotal } from './GetUTxOsStatistics200ResponseTotal';
import { PaymentPaymentsInner } from './PaymentPaymentsInner';
import { HttpFile } from '../http/http';

export class ApiCoinSelection {
    /**
    * A list of transaction inputs
    */
    'inputs': Array<ConstructTransaction202ResponseCoinSelectionInputsInner>;
    /**
    * A list of target outputs with amounts specified.
    */
    'outputs': Array<PaymentPaymentsInner>;
    /**
    * A list of transaction change outputs.
    */
    'change': Array<ConstructTransaction202ResponseCoinSelectionChangeInner>;
    /**
    * A list of transaction inputs used for collateral
    */
    'collateral'?: Array<ConstructTransaction202ResponseCoinSelectionCollateralInner>;
    /**
    * A list of withdrawals from stake addresses.
    */
    'withdrawals'?: Array<ConstructTransaction202ResponseCoinSelectionWithdrawalsInner>;
    'certificates'?: Array<ConstructTransaction202ResponseCoinSelectionCertificatesInner>;
    /**
    * A list of deposits associated with a transaction.
    */
    'depositsTaken'?: Array<GetUTxOsStatistics200ResponseTotal>;
    /**
    * A list of deposits associated with a transaction.
    */
    'depositsReturned'?: Array<GetUTxOsStatistics200ResponseTotal>;
    /**
    * Transaction metadata, serialized according to the expected on-chain binary format, base64-encoded.
    */
    'metadata'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "inputs",
            "baseName": "inputs",
            "type": "Array<ConstructTransaction202ResponseCoinSelectionInputsInner>",
            "format": ""
        },
        {
            "name": "outputs",
            "baseName": "outputs",
            "type": "Array<PaymentPaymentsInner>",
            "format": ""
        },
        {
            "name": "change",
            "baseName": "change",
            "type": "Array<ConstructTransaction202ResponseCoinSelectionChangeInner>",
            "format": ""
        },
        {
            "name": "collateral",
            "baseName": "collateral",
            "type": "Array<ConstructTransaction202ResponseCoinSelectionCollateralInner>",
            "format": ""
        },
        {
            "name": "withdrawals",
            "baseName": "withdrawals",
            "type": "Array<ConstructTransaction202ResponseCoinSelectionWithdrawalsInner>",
            "format": ""
        },
        {
            "name": "certificates",
            "baseName": "certificates",
            "type": "Array<ConstructTransaction202ResponseCoinSelectionCertificatesInner>",
            "format": ""
        },
        {
            "name": "depositsTaken",
            "baseName": "deposits_taken",
            "type": "Array<GetUTxOsStatistics200ResponseTotal>",
            "format": ""
        },
        {
            "name": "depositsReturned",
            "baseName": "deposits_returned",
            "type": "Array<GetUTxOsStatistics200ResponseTotal>",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "string",
            "format": "base64"
        }    ];

    static getAttributeTypeMap() {
        return ApiCoinSelection.attributeTypeMap;
    }

    public constructor() {
    }
}

