/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ApiDeregisterPool {
    'certificateType': ApiDeregisterPoolCertificateTypeEnum;
    /**
    * A unique identifier for the pool.
    */
    'poolId': string;
    /**
    * An epoch is a time period which is divided into slots.
    */
    'retirementEpoch': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "certificateType",
            "baseName": "certificate_type",
            "type": "ApiDeregisterPoolCertificateTypeEnum",
            "format": ""
        },
        {
            "name": "poolId",
            "baseName": "pool_id",
            "type": "string",
            "format": "hex|bech32"
        },
        {
            "name": "retirementEpoch",
            "baseName": "retirement_epoch",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiDeregisterPool.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ApiDeregisterPoolCertificateTypeEnum = "deregister_pool" ;

