/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetNetworkParameters200ResponseErasByron } from './GetNetworkParameters200ResponseErasByron';
import { HttpFile } from '../http/http';

/**
*  If and when each era started or will start.  The object is keyed by era names. The values either describe the epoch boundary when the era starts (can be in the future or in the past), or are null if not yet confirmed on-chain.  If you need to know the current era, see the `node_era` field of `GET /network/information`.  > Due to complications with our current tooling, we cannot mark the era names > as required, but the keys are in fact always present. 
*/
export class ApiEraInfo {
    'byron'?: GetNetworkParameters200ResponseErasByron;
    'shelley'?: GetNetworkParameters200ResponseErasByron;
    'allegra'?: GetNetworkParameters200ResponseErasByron;
    'mary'?: GetNetworkParameters200ResponseErasByron;
    'alonzo'?: GetNetworkParameters200ResponseErasByron;
    'babbage'?: GetNetworkParameters200ResponseErasByron;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "byron",
            "baseName": "byron",
            "type": "GetNetworkParameters200ResponseErasByron",
            "format": ""
        },
        {
            "name": "shelley",
            "baseName": "shelley",
            "type": "GetNetworkParameters200ResponseErasByron",
            "format": ""
        },
        {
            "name": "allegra",
            "baseName": "allegra",
            "type": "GetNetworkParameters200ResponseErasByron",
            "format": ""
        },
        {
            "name": "mary",
            "baseName": "mary",
            "type": "GetNetworkParameters200ResponseErasByron",
            "format": ""
        },
        {
            "name": "alonzo",
            "baseName": "alonzo",
            "type": "GetNetworkParameters200ResponseErasByron",
            "format": ""
        },
        {
            "name": "babbage",
            "baseName": "babbage",
            "type": "GetNetworkParameters200ResponseErasByron",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiEraInfo.attributeTypeMap;
    }

    public constructor() {
    }
}

