/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetMaintenanceActions200ResponseGcStakePools } from './GetMaintenanceActions200ResponseGcStakePools';
import { HttpFile } from '../http/http';

export class ApiMaintenanceAction {
    'gcStakePools': GetMaintenanceActions200ResponseGcStakePools;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "gcStakePools",
            "baseName": "gc_stake_pools",
            "type": "GetMaintenanceActions200ResponseGcStakePools",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiMaintenanceAction.attributeTypeMap;
    }

    public constructor() {
    }
}

