/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DecodeTransaction202ResponseValidityIntervalInvalidBefore } from './DecodeTransaction202ResponseValidityIntervalInvalidBefore';
import { GetNetworkParameters200ResponseActiveSlotCoefficient } from './GetNetworkParameters200ResponseActiveSlotCoefficient';
import { GetNetworkParameters200ResponseEras } from './GetNetworkParameters200ResponseEras';
import { GetNetworkParameters200ResponseExecutionUnitPrices } from './GetNetworkParameters200ResponseExecutionUnitPrices';
import { GetNetworkParameters200ResponseMaximumTokenBundleSize } from './GetNetworkParameters200ResponseMaximumTokenBundleSize';
import { GetNetworkParameters200ResponseMinimumUtxoValue } from './GetNetworkParameters200ResponseMinimumUtxoValue';
import { GetNetworkParameters200ResponseSlotLength } from './GetNetworkParameters200ResponseSlotLength';
import { ListWallets200ResponseInnerTipHeight } from './ListWallets200ResponseInnerTipHeight';
import { HttpFile } from '../http/http';

export class ApiNetworkParameters {
    /**
    * The hash of genesis block
    */
    'genesisBlockHash': string;
    'blockchainStartTime': string;
    'slotLength': GetNetworkParameters200ResponseSlotLength;
    'epochLength': DecodeTransaction202ResponseValidityIntervalInvalidBefore;
    'securityParameter': ListWallets200ResponseInnerTipHeight;
    'activeSlotCoefficient': GetNetworkParameters200ResponseActiveSlotCoefficient;
    'decentralizationLevel': GetNetworkParameters200ResponseActiveSlotCoefficient;
    'desiredPoolNumber': number;
    'minimumUtxoValue': GetNetworkParameters200ResponseMinimumUtxoValue;
    'eras': GetNetworkParameters200ResponseEras;
    /**
    * The maximum number of collateral inputs that can be used in a single transaction. 
    */
    'maximumCollateralInputCount': number;
    /**
    * The minimum required amount of collateral as a percentage of the total transaction fee. 
    */
    'minimumCollateralPercentage'?: number;
    'maximumTokenBundleSize': GetNetworkParameters200ResponseMaximumTokenBundleSize;
    'executionUnitPrices'?: GetNetworkParameters200ResponseExecutionUnitPrices;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "genesisBlockHash",
            "baseName": "genesis_block_hash",
            "type": "string",
            "format": "hex"
        },
        {
            "name": "blockchainStartTime",
            "baseName": "blockchain_start_time",
            "type": "string",
            "format": "iso-8601-date-and-time"
        },
        {
            "name": "slotLength",
            "baseName": "slot_length",
            "type": "GetNetworkParameters200ResponseSlotLength",
            "format": ""
        },
        {
            "name": "epochLength",
            "baseName": "epoch_length",
            "type": "DecodeTransaction202ResponseValidityIntervalInvalidBefore",
            "format": ""
        },
        {
            "name": "securityParameter",
            "baseName": "security_parameter",
            "type": "ListWallets200ResponseInnerTipHeight",
            "format": ""
        },
        {
            "name": "activeSlotCoefficient",
            "baseName": "active_slot_coefficient",
            "type": "GetNetworkParameters200ResponseActiveSlotCoefficient",
            "format": ""
        },
        {
            "name": "decentralizationLevel",
            "baseName": "decentralization_level",
            "type": "GetNetworkParameters200ResponseActiveSlotCoefficient",
            "format": ""
        },
        {
            "name": "desiredPoolNumber",
            "baseName": "desired_pool_number",
            "type": "number",
            "format": ""
        },
        {
            "name": "minimumUtxoValue",
            "baseName": "minimum_utxo_value",
            "type": "GetNetworkParameters200ResponseMinimumUtxoValue",
            "format": ""
        },
        {
            "name": "eras",
            "baseName": "eras",
            "type": "GetNetworkParameters200ResponseEras",
            "format": ""
        },
        {
            "name": "maximumCollateralInputCount",
            "baseName": "maximum_collateral_input_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "minimumCollateralPercentage",
            "baseName": "minimum_collateral_percentage",
            "type": "number",
            "format": ""
        },
        {
            "name": "maximumTokenBundleSize",
            "baseName": "maximum_token_bundle_size",
            "type": "GetNetworkParameters200ResponseMaximumTokenBundleSize",
            "format": ""
        },
        {
            "name": "executionUnitPrices",
            "baseName": "execution_unit_prices",
            "type": "GetNetworkParameters200ResponseExecutionUnitPrices",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiNetworkParameters.attributeTypeMap;
    }

    public constructor() {
    }
}

