/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SpendingInput } from './SpendingInput';
import { HttpFile } from '../http/http';

export class ApiRedeemerSpending {
    'purpose': ApiRedeemerSpendingPurposeEnum;
    'data': string;
    'input': SpendingInput;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "purpose",
            "baseName": "purpose",
            "type": "ApiRedeemerSpendingPurposeEnum",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "string",
            "format": "base16"
        },
        {
            "name": "input",
            "baseName": "input",
            "type": "SpendingInput",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiRedeemerSpending.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ApiRedeemerSpendingPurposeEnum = "spending" ;

