/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DelegationDelegationAction } from './DelegationDelegationAction';
import { HttpFile } from '../http/http';

export class ApiSelectCoinsAction {
    'delegationAction': DelegationDelegationAction;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "delegationAction",
            "baseName": "delegation_action",
            "type": "DelegationDelegationAction",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiSelectCoinsAction.attributeTypeMap;
    }

    public constructor() {
    }
}

