/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ActiveFromSlot } from './ActiveFromSlot';
import { ActiveUntilSlot } from './ActiveUntilSlot';
import { All1 } from './All1';
import { Any1 } from './Any1';
import { ScriptValue } from './ScriptValue';
import { Some1 } from './Some1';
import { Some1Some } from './Some1Some';
import { HttpFile } from '../http/http';

export class ApiScript {
    /**
    * Script primitive for which all signing keys corresponding to all list elements' verification keys are expected to make the script valid.
    */
    'all': Array<ScriptValue>;
    /**
    * Script primitive for which a signing key corresponding to any of the list elements' verification keys is expected to make the script valid. It is equivalent to `some` with `\"at_least\"=1`.
    */
    'any': Array<ScriptValue>;
    'some': Some1Some;
    /**
    * Transaction is only valid starting at the specified slot number (`≥ active_from`).
    */
    'activeFrom': number;
    /**
    * Transaction is only valid before the specified slot number (`< active_until`).
    */
    'activeUntil': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "all",
            "baseName": "all",
            "type": "Array<ScriptValue>",
            "format": ""
        },
        {
            "name": "any",
            "baseName": "any",
            "type": "Array<ScriptValue>",
            "format": ""
        },
        {
            "name": "some",
            "baseName": "some",
            "type": "Some1Some",
            "format": ""
        },
        {
            "name": "activeFrom",
            "baseName": "active_from",
            "type": "number",
            "format": ""
        },
        {
            "name": "activeUntil",
            "baseName": "active_until",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiScript.attributeTypeMap;
    }

    public constructor() {
    }
}

