/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentPaymentsInner } from './PaymentPaymentsInner';
import { SignMetadataRequestMetadata } from './SignMetadataRequestMetadata';
import { HttpFile } from '../http/http';

export class ApiSelectCoinsRedemption {
    /**
    * A list of target outputs with amounts specified.
    */
    'payments': Array<PaymentPaymentsInner>;
    /**
    * When provided, attempts to withdraw rewards from the default stake address corresponding to the given mnemonic.  Should the rewards be null or too small to be worth withdrawing (i.e. the cost of adding them into the transaction is more than their own intrinsic value), the server will reject the request with a `withdrawal_not_worth` error.  withdrawal field    | reward balance | result ---                 | ---            | --- any recovery phrase | too small      | x Error 403 `withdrawal_not_worth` any recovery phrase | big enough     | ✓ withdrawal generated 
    */
    'withdrawal': Array<string>;
    'metadata'?: SignMetadataRequestMetadata;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "payments",
            "baseName": "payments",
            "type": "Array<PaymentPaymentsInner>",
            "format": ""
        },
        {
            "name": "withdrawal",
            "baseName": "withdrawal",
            "type": "Array<string>",
            "format": "bip-0039-mnemonic-word{english}"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "SignMetadataRequestMetadata",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiSelectCoinsRedemption.attributeTypeMap;
    }

    public constructor() {
    }
}

