/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListStakeKeys200ResponseForeignInner } from './ListStakeKeys200ResponseForeignInner';
import { ListStakeKeys200ResponseNone } from './ListStakeKeys200ResponseNone';
import { ListStakeKeys200ResponseOursInner } from './ListStakeKeys200ResponseOursInner';
import { HttpFile } from '../http/http';

export class ApiStakeKeys {
    /**
    * Stake keys belonging to the wallet. 
    */
    'ours': Array<ListStakeKeys200ResponseOursInner>;
    /**
    * Stake keys found in the wallet's UTxO, but does not belong to the wallet. 
    */
    'foreign': Array<ListStakeKeys200ResponseForeignInner>;
    'none': ListStakeKeys200ResponseNone;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ours",
            "baseName": "ours",
            "type": "Array<ListStakeKeys200ResponseOursInner>",
            "format": ""
        },
        {
            "name": "foreign",
            "baseName": "foreign",
            "type": "Array<ListStakeKeys200ResponseForeignInner>",
            "format": ""
        },
        {
            "name": "none",
            "baseName": "none",
            "type": "ListStakeKeys200ResponseNone",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiStakeKeys.attributeTypeMap;
    }

    public constructor() {
    }
}

