/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConstructTransaction202ResponseCoinSelection } from './ConstructTransaction202ResponseCoinSelection';
import { CreateShelleyWalletMigrationPlan202ResponseBalanceLeftover } from './CreateShelleyWalletMigrationPlan202ResponseBalanceLeftover';
import { CreateShelleyWalletMigrationPlan202ResponseBalanceSelected } from './CreateShelleyWalletMigrationPlan202ResponseBalanceSelected';
import { CreateShelleyWalletMigrationPlan202ResponseTotalFee } from './CreateShelleyWalletMigrationPlan202ResponseTotalFee';
import { HttpFile } from '../http/http';

export class ApiWalletMigrationPlan {
    /**
    * The complete set of selections required for a migration.  Each selection is the basis for a single transaction.  The ordering of selections within the list is not significant. After conversion into transactions, the transactions can be broadcast to the network in any order to perform the migration. 
    */
    'selections': Array<ConstructTransaction202ResponseCoinSelection>;
    'totalFee': CreateShelleyWalletMigrationPlan202ResponseTotalFee;
    'balanceLeftover': CreateShelleyWalletMigrationPlan202ResponseBalanceLeftover;
    'balanceSelected': CreateShelleyWalletMigrationPlan202ResponseBalanceSelected;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "selections",
            "baseName": "selections",
            "type": "Array<ConstructTransaction202ResponseCoinSelection>",
            "format": ""
        },
        {
            "name": "totalFee",
            "baseName": "total_fee",
            "type": "CreateShelleyWalletMigrationPlan202ResponseTotalFee",
            "format": ""
        },
        {
            "name": "balanceLeftover",
            "baseName": "balance_leftover",
            "type": "CreateShelleyWalletMigrationPlan202ResponseBalanceLeftover",
            "format": ""
        },
        {
            "name": "balanceSelected",
            "baseName": "balance_selected",
            "type": "CreateShelleyWalletMigrationPlan202ResponseBalanceSelected",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiWalletMigrationPlan.attributeTypeMap;
    }

    public constructor() {
    }
}

