/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetWalletUtxoSnapshot200ResponseEntriesInnerAda } from './GetWalletUtxoSnapshot200ResponseEntriesInnerAda';
import { GetWalletUtxoSnapshot200ResponseEntriesInnerAdaMinimum } from './GetWalletUtxoSnapshot200ResponseEntriesInnerAdaMinimum';
import { ListWallets200ResponseInnerAssetsAvailableInner } from './ListWallets200ResponseInnerAssetsAvailableInner';
import { HttpFile } from '../http/http';

export class ApiWalletUtxoSnapshotEntry {
    'ada': GetWalletUtxoSnapshot200ResponseEntriesInnerAda;
    'adaMinimum': GetWalletUtxoSnapshot200ResponseEntriesInnerAdaMinimum;
    /**
    * The set of non-ada assets associated with this UTxO entry. 
    */
    'assets': Array<ListWallets200ResponseInnerAssetsAvailableInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ada",
            "baseName": "ada",
            "type": "GetWalletUtxoSnapshot200ResponseEntriesInnerAda",
            "format": ""
        },
        {
            "name": "adaMinimum",
            "baseName": "ada_minimum",
            "type": "GetWalletUtxoSnapshot200ResponseEntriesInnerAdaMinimum",
            "format": ""
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<ListWallets200ResponseInnerAssetsAvailableInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiWalletUtxoSnapshotEntry.attributeTypeMap;
    }

    public constructor() {
    }
}

