/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AlreadyWithdrawing } from './AlreadyWithdrawing';
import { BalanceTxByronNotSupported } from './BalanceTxByronNotSupported';
import { BalanceTxConflictingNetworks } from './BalanceTxConflictingNetworks';
import { BalanceTxExistingCollateral } from './BalanceTxExistingCollateral';
import { BalanceTxExistingCollateralReturnOutputs } from './BalanceTxExistingCollateralReturnOutputs';
import { BalanceTxExistingKeyWitnesses } from './BalanceTxExistingKeyWitnesses';
import { BalanceTxExistingTotalCollateral } from './BalanceTxExistingTotalCollateral';
import { BalanceTxInternalError } from './BalanceTxInternalError';
import { BalanceTxMaxSizeLimitExceeded } from './BalanceTxMaxSizeLimitExceeded';
import { CannotCoverFee } from './CannotCoverFee';
import { InsufficientCollateral } from './InsufficientCollateral';
import { InvalidWalletType } from './InvalidWalletType';
import { NotEnoughMoney } from './NotEnoughMoney';
import { TransactionAlreadyBalanced } from './TransactionAlreadyBalanced';
import { TransactionIsTooBig } from './TransactionIsTooBig';
import { UtxoTooSmall } from './UtxoTooSmall';
import { HttpFile } from '../http/http';

export class BalanceTransaction403Response {
    /**
    * May occur when a requested output is below the minimum utxo value.
    */
    'message': string;
    'code': BalanceTransaction403ResponseCodeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "BalanceTransaction403ResponseCodeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BalanceTransaction403Response.attributeTypeMap;
    }

    public constructor() {
    }
}


export type BalanceTransaction403ResponseCodeEnum = "utxo_too_small" ;

