/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BalanceTxExistingKeyWitnesses {
    /**
    * The transaction could not be balanced, because it contains existing key-witnesses which would be invalid after the transaction body is modified. Please sign the transaction after it is balanced instead. 
    */
    'message': string;
    'code': BalanceTxExistingKeyWitnessesCodeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "BalanceTxExistingKeyWitnessesCodeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BalanceTxExistingKeyWitnesses.attributeTypeMap;
    }

    public constructor() {
    }
}


export type BalanceTxExistingKeyWitnessesCodeEnum = "balance_tx_existing_key_witnesses" ;

