/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Minting } from './Minting';
import { Rewarding } from './Rewarding';
import { Spending } from './Spending';
import { SpendingInput } from './SpendingInput';
import { HttpFile } from '../http/http';

export class BalanceTransactionRequestRedeemersInner {
    'purpose': BalanceTransactionRequestRedeemersInnerPurposeEnum;
    'data': string;
    'input': SpendingInput;
    'policyId': string;
    'stakeAddress': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "purpose",
            "baseName": "purpose",
            "type": "BalanceTransactionRequestRedeemersInnerPurposeEnum",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "string",
            "format": "base16"
        },
        {
            "name": "input",
            "baseName": "input",
            "type": "SpendingInput",
            "format": ""
        },
        {
            "name": "policyId",
            "baseName": "policy_id",
            "type": "string",
            "format": "hex"
        },
        {
            "name": "stakeAddress",
            "baseName": "stake_address",
            "type": "string",
            "format": "bech32"
        }    ];

    static getAttributeTypeMap() {
        return BalanceTransactionRequestRedeemersInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export type BalanceTransactionRequestRedeemersInnerPurposeEnum = "rewarding" ;

