/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BadRequest } from './BadRequest';
import { RedeemerInvalidData } from './RedeemerInvalidData';
import { RedeemerScriptFailure } from './RedeemerScriptFailure';
import { RedeemerTargetNotFound } from './RedeemerTargetNotFound';
import { TranslationError } from './TranslationError';
import { UnresolvedInputs } from './UnresolvedInputs';
import { HttpFile } from '../http/http';

export class BalanceTransaction400Response {
    /**
    * Occurs when any data in a provided transaction cannot be translated in a given era 
    */
    'message': string;
    'code': BalanceTransaction400ResponseCodeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "BalanceTransaction400ResponseCodeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BalanceTransaction400Response.attributeTypeMap;
    }

    public constructor() {
    }
}


export type BalanceTransaction400ResponseCodeEnum = "translation_error" ;

