/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AlreadyWithdrawing } from './AlreadyWithdrawing';
import { AssetNameTooLong } from './AssetNameTooLong';
import { CannotCoverFee } from './CannotCoverFee';
import { CreatedMultiaccountTransaction } from './CreatedMultiaccountTransaction';
import { CreatedMultidelegationTransaction } from './CreatedMultidelegationTransaction';
import { CreatedWrongPolicyScriptTemplate } from './CreatedWrongPolicyScriptTemplate';
import { InsufficientCollateral } from './InsufficientCollateral';
import { InvalidValidityBounds } from './InvalidValidityBounds';
import { InvalidWalletType } from './InvalidWalletType';
import { MintOrBurnAssetQuantityOutOfBounds } from './MintOrBurnAssetQuantityOutOfBounds';
import { NotEnoughMoney } from './NotEnoughMoney';
import { SharedWalletPending } from './SharedWalletPending';
import { TransactionIsTooBig } from './TransactionIsTooBig';
import { UtxoTooSmall } from './UtxoTooSmall';
import { ValidityIntervalNotInsideScriptTimelock } from './ValidityIntervalNotInsideScriptTimelock';
import { HttpFile } from '../http/http';

export class ConstructTransaction403Response {
    /**
    * Occurs when attempting to create a transaction for a pending shared wallet.
    */
    'message': string;
    'code': ConstructTransaction403ResponseCodeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "ConstructTransaction403ResponseCodeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConstructTransaction403Response.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ConstructTransaction403ResponseCodeEnum = "shared_wallet_pending" ;

