/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConstructTransactionRequestValidityIntervalInvalidBefore } from './ConstructTransactionRequestValidityIntervalInvalidBefore';
import { HttpFile } from '../http/http';

/**
* Specify only invalid_before or invalid_hereafter or both.  Please note that, if not set, the default values are:   - `\"invalid_before\": {\"quantity\":0, \"unit\":\"slot\"}`   - `\"invalid_hereafter\":{\"quantity\":7200, \"unit\":\"second\"}`  Which translates to 2h transaction TTL. 
*/
export class ConstructTransactionRequestValidityInterval {
    'invalidBefore'?: ConstructTransactionRequestValidityIntervalInvalidBefore;
    'invalidHereafter'?: ConstructTransactionRequestValidityIntervalInvalidBefore;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "invalidBefore",
            "baseName": "invalid_before",
            "type": "ConstructTransactionRequestValidityIntervalInvalidBefore",
            "format": ""
        },
        {
            "name": "invalidHereafter",
            "baseName": "invalid_hereafter",
            "type": "ConstructTransactionRequestValidityIntervalInvalidBefore",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConstructTransactionRequestValidityInterval.attributeTypeMap;
    }

    public constructor() {
    }
}

