/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Burn } from './Burn';
import { BurnBurn } from './BurnBurn';
import { Mint } from './Mint';
import { MintMint } from './MintMint';
import { HttpFile } from '../http/http';

export class ConstructTransactionRequestMintBurnInnerOperation {
    'mint'?: MintMint;
    'burn'?: BurnBurn;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mint",
            "baseName": "mint",
            "type": "MintMint",
            "format": ""
        },
        {
            "name": "burn",
            "baseName": "burn",
            "type": "BurnBurn",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConstructTransactionRequestMintBurnInnerOperation.attributeTypeMap;
    }

    public constructor() {
    }
}

