/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConstructTransactionRequestMintBurnInnerOperation } from './ConstructTransactionRequestMintBurnInnerOperation';
import { ConstructTransactionRequestMintBurnInnerPolicyScriptTemplate } from './ConstructTransactionRequestMintBurnInnerPolicyScriptTemplate';
import { HttpFile } from '../http/http';

export class ConstructTransactionRequestMintBurnInner {
    'policyScriptTemplate': ConstructTransactionRequestMintBurnInnerPolicyScriptTemplate;
    /**
    * The asset on-chain type which acts as a sub-identifier within a policy. Although we call it \"asset name\", the value needn't be text, and it could even be empty.  For policies with a single fungible asset item, asset name is typically an empty string.  This value can be up to 32 bytes of arbitrary data (which is 64 hexadecimal digits). 
    */
    'assetName'?: string;
    'operation': ConstructTransactionRequestMintBurnInnerOperation;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "policyScriptTemplate",
            "baseName": "policy_script_template",
            "type": "ConstructTransactionRequestMintBurnInnerPolicyScriptTemplate",
            "format": ""
        },
        {
            "name": "assetName",
            "baseName": "asset_name",
            "type": "string",
            "format": "hex"
        },
        {
            "name": "operation",
            "baseName": "operation",
            "type": "ConstructTransactionRequestMintBurnInnerOperation",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConstructTransactionRequestMintBurnInner.attributeTypeMap;
    }

    public constructor() {
    }
}

