/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConstructTransactionRequestDelegationsInnerOneOf } from './ConstructTransactionRequestDelegationsInnerOneOf';
import { ConstructTransactionRequestDelegationsInnerOneOf1 } from './ConstructTransactionRequestDelegationsInnerOneOf1';
import { ConstructTransactionRequestDelegationsInnerOneOf1Quit } from './ConstructTransactionRequestDelegationsInnerOneOf1Quit';
import { ConstructTransactionRequestDelegationsInnerOneOfJoin } from './ConstructTransactionRequestDelegationsInnerOneOfJoin';
import { HttpFile } from '../http/http';

/**
* A delegation action for a given stake key denoted by its soft index. Pool id is only required for \"join\". Stake key index are required for both actions. 
*/
export class ConstructTransactionRequestDelegationsInner {
    'join': ConstructTransactionRequestDelegationsInnerOneOfJoin;
    'quit': ConstructTransactionRequestDelegationsInnerOneOf1Quit;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "join",
            "baseName": "join",
            "type": "ConstructTransactionRequestDelegationsInnerOneOfJoin",
            "format": ""
        },
        {
            "name": "quit",
            "baseName": "quit",
            "type": "ConstructTransactionRequestDelegationsInnerOneOf1Quit",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConstructTransactionRequestDelegationsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

