/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The total amount to be paid in fees for a migration.  This is the total sum of the fees of the individual selections. 
*/
export class CreateShelleyWalletMigrationPlan202ResponseTotalFee {
    'quantity': number;
    'unit': CreateShelleyWalletMigrationPlan202ResponseTotalFeeUnitEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "CreateShelleyWalletMigrationPlan202ResponseTotalFeeUnitEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateShelleyWalletMigrationPlan202ResponseTotalFee.attributeTypeMap;
    }

    public constructor() {
    }
}


export type CreateShelleyWalletMigrationPlan202ResponseTotalFeeUnitEnum = "lovelace" ;

