/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DecodeTransaction202ResponseMintTokensInnerPolicyScriptOneOf } from './DecodeTransaction202ResponseMintTokensInnerPolicyScriptOneOf';
import { DecodeTransaction202ResponseMintTokensInnerPolicyScriptOneOf1 } from './DecodeTransaction202ResponseMintTokensInnerPolicyScriptOneOf1';
import { DecodeTransaction202ResponseMintTokensInnerPolicyScriptOneOfScript } from './DecodeTransaction202ResponseMintTokensInnerPolicyScriptOneOfScript';
import { HttpFile } from '../http/http';

export class DecodeTransaction202ResponseMintTokensInnerPolicyScript {
    'scriptType': DecodeTransaction202ResponseMintTokensInnerPolicyScriptScriptTypeEnum;
    'script': DecodeTransaction202ResponseMintTokensInnerPolicyScriptOneOfScript;
    'languageVersion': DecodeTransaction202ResponseMintTokensInnerPolicyScriptLanguageVersionEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "scriptType",
            "baseName": "script_type",
            "type": "DecodeTransaction202ResponseMintTokensInnerPolicyScriptScriptTypeEnum",
            "format": ""
        },
        {
            "name": "script",
            "baseName": "script",
            "type": "DecodeTransaction202ResponseMintTokensInnerPolicyScriptOneOfScript",
            "format": ""
        },
        {
            "name": "languageVersion",
            "baseName": "language_version",
            "type": "DecodeTransaction202ResponseMintTokensInnerPolicyScriptLanguageVersionEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DecodeTransaction202ResponseMintTokensInnerPolicyScript.attributeTypeMap;
    }

    public constructor() {
    }
}


export type DecodeTransaction202ResponseMintTokensInnerPolicyScriptScriptTypeEnum = "plutus" ;
export type DecodeTransaction202ResponseMintTokensInnerPolicyScriptLanguageVersionEnum = "v1" | "v2" ;

