/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DecodeTransaction202ResponseMintTokensInnerAssetsInner } from './DecodeTransaction202ResponseMintTokensInnerAssetsInner';
import { DecodeTransaction202ResponseMintTokensInnerPolicyScript } from './DecodeTransaction202ResponseMintTokensInnerPolicyScript';
import { HttpFile } from '../http/http';

export class DecodeTransaction202ResponseMintTokensInner {
    /**
    * A unique identifier of the asset's monetary policy. The policy controls how assets of this kind are created and destroyed.  The contents are the blake2b-224 hash of the monetary policy script, encoded in hexadecimal. 
    */
    'policyId': string;
    'policyScript': DecodeTransaction202ResponseMintTokensInnerPolicyScript;
    'assets': Array<DecodeTransaction202ResponseMintTokensInnerAssetsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "policyId",
            "baseName": "policy_id",
            "type": "string",
            "format": "hex"
        },
        {
            "name": "policyScript",
            "baseName": "policy_script",
            "type": "DecodeTransaction202ResponseMintTokensInnerPolicyScript",
            "format": ""
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<DecodeTransaction202ResponseMintTokensInnerAssetsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DecodeTransaction202ResponseMintTokensInner.attributeTypeMap;
    }

    public constructor() {
    }
}

