/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DecodeTransaction202ResponseMintTokensInnerPolicyScriptOneOf1 {
    'scriptType': DecodeTransaction202ResponseMintTokensInnerPolicyScriptOneOf1ScriptTypeEnum;
    'languageVersion': DecodeTransaction202ResponseMintTokensInnerPolicyScriptOneOf1LanguageVersionEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "scriptType",
            "baseName": "script_type",
            "type": "DecodeTransaction202ResponseMintTokensInnerPolicyScriptOneOf1ScriptTypeEnum",
            "format": ""
        },
        {
            "name": "languageVersion",
            "baseName": "language_version",
            "type": "DecodeTransaction202ResponseMintTokensInnerPolicyScriptOneOf1LanguageVersionEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DecodeTransaction202ResponseMintTokensInnerPolicyScriptOneOf1.attributeTypeMap;
    }

    public constructor() {
    }
}


export type DecodeTransaction202ResponseMintTokensInnerPolicyScriptOneOf1ScriptTypeEnum = "plutus" ;
export type DecodeTransaction202ResponseMintTokensInnerPolicyScriptOneOf1LanguageVersionEnum = "v1" | "v2" ;

