/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetUTxOsStatistics200ResponseTotal } from './GetUTxOsStatistics200ResponseTotal';
import { ListWallets200ResponseInnerAssetsAvailableInner } from './ListWallets200ResponseInnerAssetsAvailableInner';
import { TxInputsBelongingToAGivenWallet } from './TxInputsBelongingToAGivenWallet';
import { TxInputsWithoutSourceNotBelongingToAGivenWallet } from './TxInputsWithoutSourceNotBelongingToAGivenWallet';
import { HttpFile } from '../http/http';

export class DecodeTransaction202ResponseInputsInner {
    /**
    * A unique identifier for this transaction
    */
    'id': string;
    'index': number;
    /**
    * A sequence of characters that encodes (in Base58 or Bech32) a sequence of bytes which represents an address on the Cardano blockchain. Sequences in Base58 encoding are expected to be legacy Byron addresses, whereas sequences in Bech32 encoding correspond to current Shelley addresses.  For more details, see [CIP-0019 — Cardano addresses](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0019) . 
    */
    'address': string;
    'amount': GetUTxOsStatistics200ResponseTotal;
    /**
    * A flat list of assets (possibly empty).
    */
    'assets'?: Array<ListWallets200ResponseInnerAssetsAvailableInner>;
    /**
    * A path for deriving a child key from a parent key.
    */
    'derivationPath': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "hex"
        },
        {
            "name": "index",
            "baseName": "index",
            "type": "number",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": "base58|bech32"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "GetUTxOsStatistics200ResponseTotal",
            "format": ""
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<ListWallets200ResponseInnerAssetsAvailableInner>",
            "format": ""
        },
        {
            "name": "derivationPath",
            "baseName": "derivation_path",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DecodeTransaction202ResponseInputsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

