/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A delegation certificate not belonging to wallet  Only for 'join_pool' the 'pool' property is required. 
*/
export class DelegationCertificateNotBelongingToTheWallet {
    'certificateType': DelegationCertificateNotBelongingToTheWalletCertificateTypeEnum;
    /**
    * A unique identifier for the pool.
    */
    'pool'?: string;
    'rewardAccount': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "certificateType",
            "baseName": "certificate_type",
            "type": "DelegationCertificateNotBelongingToTheWalletCertificateTypeEnum",
            "format": ""
        },
        {
            "name": "pool",
            "baseName": "pool",
            "type": "string",
            "format": "hex|bech32"
        },
        {
            "name": "rewardAccount",
            "baseName": "reward_account",
            "type": "string",
            "format": "bech32"
        }    ];

    static getAttributeTypeMap() {
        return DelegationCertificateNotBelongingToTheWallet.attributeTypeMap;
    }

    public constructor() {
    }
}


export type DelegationCertificateNotBelongingToTheWalletCertificateTypeEnum = "join_pool_external" | "quit_pool_external" | "register_reward_account_external" ;

