/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetNetworkInformation200ResponseNetworkInfo } from './GetNetworkInformation200ResponseNetworkInfo';
import { GetNetworkInformation200ResponseNetworkTip } from './GetNetworkInformation200ResponseNetworkTip';
import { GetNetworkInformation200ResponseNodeTip } from './GetNetworkInformation200ResponseNodeTip';
import { GetNetworkInformation200ResponseSyncProgress } from './GetNetworkInformation200ResponseSyncProgress';
import { ListWallets200ResponseInnerDelegationNextInnerChangesAt } from './ListWallets200ResponseInnerDelegationNextInnerChangesAt';
import { HttpFile } from '../http/http';

export class GetNetworkInformation200Response {
    'syncProgress': GetNetworkInformation200ResponseSyncProgress;
    'nodeTip': GetNetworkInformation200ResponseNodeTip;
    'networkTip'?: GetNetworkInformation200ResponseNetworkTip;
    'nextEpoch'?: ListWallets200ResponseInnerDelegationNextInnerChangesAt;
    'nodeEra': GetNetworkInformation200ResponseNodeEraEnum;
    'networkInfo': GetNetworkInformation200ResponseNetworkInfo;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "syncProgress",
            "baseName": "sync_progress",
            "type": "GetNetworkInformation200ResponseSyncProgress",
            "format": ""
        },
        {
            "name": "nodeTip",
            "baseName": "node_tip",
            "type": "GetNetworkInformation200ResponseNodeTip",
            "format": ""
        },
        {
            "name": "networkTip",
            "baseName": "network_tip",
            "type": "GetNetworkInformation200ResponseNetworkTip",
            "format": ""
        },
        {
            "name": "nextEpoch",
            "baseName": "next_epoch",
            "type": "ListWallets200ResponseInnerDelegationNextInnerChangesAt",
            "format": ""
        },
        {
            "name": "nodeEra",
            "baseName": "node_era",
            "type": "GetNetworkInformation200ResponseNodeEraEnum",
            "format": ""
        },
        {
            "name": "networkInfo",
            "baseName": "network_info",
            "type": "GetNetworkInformation200ResponseNetworkInfo",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetNetworkInformation200Response.attributeTypeMap;
    }

    public constructor() {
    }
}


export type GetNetworkInformation200ResponseNodeEraEnum = "byron" | "shelley" | "allegra" | "mary" | "alonzo" | "babbage" ;

