/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GetNetworkInformation200ResponseNetworkInfo {
    /**
    * The unique magic number defining the network the wallet is working on.
    */
    'protocolMagic': number;
    /**
    * A name just distinguishing mainnet from testnets
    */
    'networkId': GetNetworkInformation200ResponseNetworkInfoNetworkIdEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "protocolMagic",
            "baseName": "protocol_magic",
            "type": "number",
            "format": ""
        },
        {
            "name": "networkId",
            "baseName": "network_id",
            "type": "GetNetworkInformation200ResponseNetworkInfoNetworkIdEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetNetworkInformation200ResponseNetworkInfo.attributeTypeMap;
    }

    public constructor() {
    }
}


export type GetNetworkInformation200ResponseNetworkInfoNetworkIdEnum = "mainnet" | "testnet" ;

