/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetNetworkClock200ResponseOffset } from './GetNetworkClock200ResponseOffset';
import { HttpFile } from '../http/http';

/**
* [Network Time Protocol](https://en.wikipedia.org/wiki/Network_Time_Protocol) information of the server.  **Important:** This piece of information only makes sense when the server runs on the same host machine as the node. 
*/
export class GetNetworkClock200Response {
    'status': GetNetworkClock200ResponseStatusEnum;
    'offset'?: GetNetworkClock200ResponseOffset;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "GetNetworkClock200ResponseStatusEnum",
            "format": ""
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "GetNetworkClock200ResponseOffset",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetNetworkClock200Response.attributeTypeMap;
    }

    public constructor() {
    }
}


export type GetNetworkClock200ResponseStatusEnum = "available" | "unavailable" | "pending" ;

