/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetNetworkParameters200ResponseExecutionUnitPricesStepPrice } from './GetNetworkParameters200ResponseExecutionUnitPricesStepPrice';
import { HttpFile } from '../http/http';

/**
* The price of time unit and memory unit used for calculating a fee of a script execution. 
*/
export class GetNetworkParameters200ResponseExecutionUnitPrices {
    'stepPrice': GetNetworkParameters200ResponseExecutionUnitPricesStepPrice;
    'memoryUnitPrice': GetNetworkParameters200ResponseExecutionUnitPricesStepPrice;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "stepPrice",
            "baseName": "step_price",
            "type": "GetNetworkParameters200ResponseExecutionUnitPricesStepPrice",
            "format": ""
        },
        {
            "name": "memoryUnitPrice",
            "baseName": "memory_unit_price",
            "type": "GetNetworkParameters200ResponseExecutionUnitPricesStepPrice",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetNetworkParameters200ResponseExecutionUnitPrices.attributeTypeMap;
    }

    public constructor() {
    }
}

