/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InvalidWalletType } from './InvalidWalletType';
import { MissingPolicyPublicKey } from './MissingPolicyPublicKey';
import { HttpFile } from '../http/http';

export class GetPolicyKey403Response {
    /**
    * Occurs when trying to construct with minting/burning on shelley wallet without policy public key.
    */
    'message': string;
    'code': GetPolicyKey403ResponseCodeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "GetPolicyKey403ResponseCodeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetPolicyKey403Response.attributeTypeMap;
    }

    public constructor() {
    }
}


export type GetPolicyKey403ResponseCodeEnum = "missing_policy_public_key" ;

