/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetUTxOsStatistics200ResponseTotal } from './GetUTxOsStatistics200ResponseTotal';
import { HttpFile } from '../http/http';

export class GetUTxOsStatistics200Response {
    'total': GetUTxOsStatistics200ResponseTotal;
    'scale': GetUTxOsStatistics200ResponseScaleEnum;
    'distribution': { [key: string]: number; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "total",
            "baseName": "total",
            "type": "GetUTxOsStatistics200ResponseTotal",
            "format": ""
        },
        {
            "name": "scale",
            "baseName": "scale",
            "type": "GetUTxOsStatistics200ResponseScaleEnum",
            "format": ""
        },
        {
            "name": "distribution",
            "baseName": "distribution",
            "type": "{ [key: string]: number; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetUTxOsStatistics200Response.attributeTypeMap;
    }

    public constructor() {
    }
}


export type GetUTxOsStatistics200ResponseScaleEnum = "log10" ;

