/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Coins, in Lovelace. Only relates to 'Ada'. Refer to `assets` for multi-assets wallets instead.
*/
export class GetUTxOsStatistics200ResponseTotal {
    'quantity': number;
    'unit': GetUTxOsStatistics200ResponseTotalUnitEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "GetUTxOsStatistics200ResponseTotalUnitEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetUTxOsStatistics200ResponseTotal.attributeTypeMap;
    }

    public constructor() {
    }
}


export type GetUTxOsStatistics200ResponseTotalUnitEnum = "lovelace" ;

