/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetWalletUtxoSnapshot200ResponseEntriesInner } from './GetWalletUtxoSnapshot200ResponseEntriesInner';
import { HttpFile } from '../http/http';

export class GetWalletUtxoSnapshot200Response {
    /**
    * The complete set of UTxO entries associated with a wallet. 
    */
    'entries': Array<GetWalletUtxoSnapshot200ResponseEntriesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "entries",
            "baseName": "entries",
            "type": "Array<GetWalletUtxoSnapshot200ResponseEntriesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetWalletUtxoSnapshot200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

