/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class InvalidValidityBounds {
    /**
    * Occurs when attempting to create a transaction with invalid validity bounds. The 'invalid_before' bound must precede the 'invalid_hereafter' bound, and the given time values must not be negative.
    */
    'message': string;
    'code': InvalidValidityBoundsCodeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "InvalidValidityBoundsCodeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InvalidValidityBounds.attributeTypeMap;
    }

    public constructor() {
    }
}


export type InvalidValidityBoundsCodeEnum = "invalid_validity_bounds" ;

