/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { URI } from './URI';
import { HttpFile } from '../http/http';

/**
* Information about the stake pool. 
*/
export class ListStakePools200ResponseInnerMetadata {
    'ticker': string;
    'name': string;
    'description'?: string;
    'homepage': URI;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ticker",
            "baseName": "ticker",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "homepage",
            "baseName": "homepage",
            "type": "URI",
            "format": "uri"
        }    ];

    static getAttributeTypeMap() {
        return ListStakePools200ResponseInnerMetadata.attributeTypeMap;
    }

    public constructor() {
    }
}

