/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* <span style=\"position: relative; left: 35px; top: -21px; vertical-align: middle; background-color: rgba(142, 142, 220, 0.05); color: rgba(50, 50, 159, 0.9); margin: 0 5px; padding: 0 5px; border: 1px solid rgba(50, 50, 159, 0.1); line-height: 20px; font-size: 13px; border-radius: 2px;\"> <strong>if:</strong> status == pending OR status == expired </span><br/> Absolute time and slot at which the pending transaction TTL (time to live) will lapse. 
*/
export class ListTransactions200ResponseInnerExpiresAt {
    /**
    * The 0-based slot index starting from genesis of the blockchain.
    */
    'absoluteSlotNumber': number;
    /**
    * An epoch is a time period which is divided into slots.
    */
    'epochNumber': number;
    /**
    * The zero-based slot index within an epoch.
    */
    'slotNumber': number;
    'time': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "absoluteSlotNumber",
            "baseName": "absolute_slot_number",
            "type": "number",
            "format": ""
        },
        {
            "name": "epochNumber",
            "baseName": "epoch_number",
            "type": "number",
            "format": ""
        },
        {
            "name": "slotNumber",
            "baseName": "slot_number",
            "type": "number",
            "format": ""
        },
        {
            "name": "time",
            "baseName": "time",
            "type": "string",
            "format": "iso-8601-date-and-time"
        }    ];

    static getAttributeTypeMap() {
        return ListTransactions200ResponseInnerExpiresAt.attributeTypeMap;
    }

    public constructor() {
    }
}

