/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListStakePools200ResponseInnerMetricsNonMyopicMemberRewards } from './ListStakePools200ResponseInnerMetricsNonMyopicMemberRewards';
import { ListStakePools200ResponseInnerMetricsProducedBlocks } from './ListStakePools200ResponseInnerMetricsProducedBlocks';
import { ListStakePools200ResponseInnerMetricsRelativeStake } from './ListStakePools200ResponseInnerMetricsRelativeStake';
import { HttpFile } from '../http/http';

export class ListStakePools200ResponseInnerMetrics {
    'nonMyopicMemberRewards': ListStakePools200ResponseInnerMetricsNonMyopicMemberRewards;
    'relativeStake': ListStakePools200ResponseInnerMetricsRelativeStake;
    /**
    * Saturation-level of the pool based on the desired number of pools aimed by the network. A value above `1` indicates that the pool is saturated.  The `non_myopic_member_rewards` take oversaturation into account, as specified by the [specs](https://hydra.iohk.io/job/Cardano/cardano-ledger-specs/delegationDesignSpec/latest/download-by-type/doc-pdf/delegation_design_spec).  The saturation is based on the live `relative_stake`. The saturation at the end of epoch e, will affect the rewards paid out at the end of epoch e+3. 
    */
    'saturation': number;
    'producedBlocks': ListStakePools200ResponseInnerMetricsProducedBlocks;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "nonMyopicMemberRewards",
            "baseName": "non_myopic_member_rewards",
            "type": "ListStakePools200ResponseInnerMetricsNonMyopicMemberRewards",
            "format": ""
        },
        {
            "name": "relativeStake",
            "baseName": "relative_stake",
            "type": "ListStakePools200ResponseInnerMetricsRelativeStake",
            "format": ""
        },
        {
            "name": "saturation",
            "baseName": "saturation",
            "type": "number",
            "format": ""
        },
        {
            "name": "producedBlocks",
            "baseName": "produced_blocks",
            "type": "ListStakePools200ResponseInnerMetricsProducedBlocks",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListStakePools200ResponseInnerMetrics.attributeTypeMap;
    }

    public constructor() {
    }
}

