/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListWallets200ResponseInnerStateProgress } from './ListWallets200ResponseInnerStateProgress';
import { HttpFile } from '../http/http';

/**
* Whether a wallet is ready to use or still syncing
*/
export class ListWallets200ResponseInnerState {
    'status': ListWallets200ResponseInnerStateStatusEnum;
    'progress'?: ListWallets200ResponseInnerStateProgress;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "ListWallets200ResponseInnerStateStatusEnum",
            "format": ""
        },
        {
            "name": "progress",
            "baseName": "progress",
            "type": "ListWallets200ResponseInnerStateProgress",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListWallets200ResponseInnerState.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ListWallets200ResponseInnerStateStatusEnum = "ready" | "syncing" | "not_responding" ;

