/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListStakePools200ResponseInnerMetadata } from './ListStakePools200ResponseInnerMetadata';
import { ListStakePools200ResponseInnerMetrics } from './ListStakePools200ResponseInnerMetrics';
import { ListStakePools200ResponseInnerRetirement } from './ListStakePools200ResponseInnerRetirement';
import { PoolRegistrationCertificatePoolCost } from './PoolRegistrationCertificatePoolCost';
import { PoolRegistrationCertificatePoolMargin } from './PoolRegistrationCertificatePoolMargin';
import { PoolRegistrationCertificatePoolPledge } from './PoolRegistrationCertificatePoolPledge';
import { HttpFile } from '../http/http';

export class ListStakePools200ResponseInner {
    /**
    * A unique identifier for the pool.
    */
    'id': string;
    'metrics': ListStakePools200ResponseInnerMetrics;
    'cost': PoolRegistrationCertificatePoolCost;
    'margin': PoolRegistrationCertificatePoolMargin;
    'pledge': PoolRegistrationCertificatePoolPledge;
    'metadata'?: ListStakePools200ResponseInnerMetadata;
    'retirement'?: ListStakePools200ResponseInnerRetirement;
    /**
    * Various flags applicable to stake pools. Possible flags:  | flag     | description                                                                                                      | | ---      | ---                                                                                                              | | delisted | The pool is marked as delisted on a configured SMASH server; metadata for this pool have therefore been dropped. | 
    */
    'flags': Array<ListStakePools200ResponseInnerFlagsEnum>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "hex|bech32"
        },
        {
            "name": "metrics",
            "baseName": "metrics",
            "type": "ListStakePools200ResponseInnerMetrics",
            "format": ""
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "PoolRegistrationCertificatePoolCost",
            "format": ""
        },
        {
            "name": "margin",
            "baseName": "margin",
            "type": "PoolRegistrationCertificatePoolMargin",
            "format": ""
        },
        {
            "name": "pledge",
            "baseName": "pledge",
            "type": "PoolRegistrationCertificatePoolPledge",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "ListStakePools200ResponseInnerMetadata",
            "format": ""
        },
        {
            "name": "retirement",
            "baseName": "retirement",
            "type": "ListStakePools200ResponseInnerRetirement",
            "format": ""
        },
        {
            "name": "flags",
            "baseName": "flags",
            "type": "Array<ListStakePools200ResponseInnerFlagsEnum>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListStakePools200ResponseInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ListStakePools200ResponseInnerFlagsEnum = "delisted" ;

