/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListByronWallets200ResponseInnerBalanceAvailable } from './ListByronWallets200ResponseInnerBalanceAvailable';
import { ListByronWallets200ResponseInnerBalanceTotal } from './ListByronWallets200ResponseInnerBalanceTotal';
import { HttpFile } from '../http/http';

/**
* Byron wallet's current balance(s)
*/
export class ListByronWallets200ResponseInnerBalance {
    'available': ListByronWallets200ResponseInnerBalanceAvailable;
    'total': ListByronWallets200ResponseInnerBalanceTotal;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "available",
            "baseName": "available",
            "type": "ListByronWallets200ResponseInnerBalanceAvailable",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "ListByronWallets200ResponseInnerBalanceTotal",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListByronWallets200ResponseInnerBalance.attributeTypeMap;
    }

    public constructor() {
    }
}

