/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListWallets200ResponseInnerTipHeight } from './ListWallets200ResponseInnerTipHeight';
import { HttpFile } from '../http/http';

/**
* A reference to a particular time slot, and the block height at that point.
*/
export class ListWallets200ResponseInnerTip {
    /**
    * The 0-based slot index starting from genesis of the blockchain.
    */
    'absoluteSlotNumber': number;
    /**
    * The zero-based slot index within an epoch.
    */
    'slotNumber': number;
    /**
    * An epoch is a time period which is divided into slots.
    */
    'epochNumber': number;
    'time': string;
    'height': ListWallets200ResponseInnerTipHeight;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "absoluteSlotNumber",
            "baseName": "absolute_slot_number",
            "type": "number",
            "format": ""
        },
        {
            "name": "slotNumber",
            "baseName": "slot_number",
            "type": "number",
            "format": ""
        },
        {
            "name": "epochNumber",
            "baseName": "epoch_number",
            "type": "number",
            "format": ""
        },
        {
            "name": "time",
            "baseName": "time",
            "type": "string",
            "format": "iso-8601-date-and-time"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "ListWallets200ResponseInnerTipHeight",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListWallets200ResponseInnerTip.attributeTypeMap;
    }

    public constructor() {
    }
}

