/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Information about the wallet's passphrase
*/
export class ListWallets200ResponseInnerPassphrase {
    'lastUpdatedAt': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "lastUpdatedAt",
            "baseName": "last_updated_at",
            "type": "string",
            "format": "iso-8601-date-and-time"
        }    ];

    static getAttributeTypeMap() {
        return ListWallets200ResponseInnerPassphrase.attributeTypeMap;
    }

    public constructor() {
    }
}

