/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListWallets200ResponseInnerBalanceAvailable } from './ListWallets200ResponseInnerBalanceAvailable';
import { ListWallets200ResponseInnerBalanceReward } from './ListWallets200ResponseInnerBalanceReward';
import { ListWallets200ResponseInnerBalanceTotal } from './ListWallets200ResponseInnerBalanceTotal';
import { HttpFile } from '../http/http';

/**
* Wallet current Ada balance(s).
*/
export class ListWallets200ResponseInnerBalance {
    'available': ListWallets200ResponseInnerBalanceAvailable;
    'reward': ListWallets200ResponseInnerBalanceReward;
    'total': ListWallets200ResponseInnerBalanceTotal;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "available",
            "baseName": "available",
            "type": "ListWallets200ResponseInnerBalanceAvailable",
            "format": ""
        },
        {
            "name": "reward",
            "baseName": "reward",
            "type": "ListWallets200ResponseInnerBalanceReward",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "ListWallets200ResponseInnerBalanceTotal",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListWallets200ResponseInnerBalance.attributeTypeMap;
    }

    public constructor() {
    }
}

