/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetUTxOsStatistics200ResponseTotal } from './GetUTxOsStatistics200ResponseTotal';
import { ListTransactions200ResponseInnerAmount } from './ListTransactions200ResponseInnerAmount';
import { ListTransactions200ResponseInnerCollateralInner } from './ListTransactions200ResponseInnerCollateralInner';
import { ListTransactions200ResponseInnerDepth } from './ListTransactions200ResponseInnerDepth';
import { ListTransactions200ResponseInnerExpiresAt } from './ListTransactions200ResponseInnerExpiresAt';
import { ListTransactions200ResponseInnerInputsInner } from './ListTransactions200ResponseInnerInputsInner';
import { ListTransactions200ResponseInnerInsertedAt } from './ListTransactions200ResponseInnerInsertedAt';
import { ListTransactions200ResponseInnerPendingSince } from './ListTransactions200ResponseInnerPendingSince';
import { ListTransactions200ResponseInnerWithdrawalsInner } from './ListTransactions200ResponseInnerWithdrawalsInner';
import { PaymentPaymentsInner } from './PaymentPaymentsInner';
import { SignMetadataRequestMetadata } from './SignMetadataRequestMetadata';
import { HttpFile } from '../http/http';

export class ListTransactions200ResponseInner {
    /**
    * A unique identifier for this transaction
    */
    'id': string;
    'amount': ListTransactions200ResponseInnerAmount;
    'fee': GetUTxOsStatistics200ResponseTotal;
    'depositTaken': GetUTxOsStatistics200ResponseTotal;
    'depositReturned': GetUTxOsStatistics200ResponseTotal;
    'insertedAt'?: ListTransactions200ResponseInnerInsertedAt;
    'expiresAt'?: ListTransactions200ResponseInnerExpiresAt;
    'pendingSince'?: ListTransactions200ResponseInnerPendingSince;
    'depth'?: ListTransactions200ResponseInnerDepth;
    'direction': ListTransactions200ResponseInnerDirectionEnum;
    /**
    * A list of transaction inputs.  `assets` and `address` are always present for `outgoing` transactions but generally absent for `incoming` transactions. This information is present on the Cardano explorer, but is not tracked by the wallet. 
    */
    'inputs': Array<ListTransactions200ResponseInnerInputsInner>;
    /**
    * A list of target outputs with amounts specified.
    */
    'outputs': Array<PaymentPaymentsInner>;
    /**
    * A list of transaction inputs used for collateral. 
    */
    'collateral'?: Array<ListTransactions200ResponseInnerCollateralInner>;
    /**
    * A list of collateral return outputs with amounts specified.
    */
    'collateralOutputs'?: Array<PaymentPaymentsInner>;
    /**
    * A list of withdrawals from stake addresses.
    */
    'withdrawals': Array<ListTransactions200ResponseInnerWithdrawalsInner>;
    /**
    * Current transaction status.    ```        *-----------*   ---> |  PENDING  |----------------*        *-----------*                |              |                      |              V                      V        *-----------*          *-----------*        |           |---------->  EXPIRED  |        |           |  (ttl)   *-----------*        | SUBMITTED |        |           <----------------*        |           |                |        *-----------*           (rollback)               |                     |          (in ledger)          *-----------*               |               |           |               *---------------> IN_LEDGER |                               |           |                               *-----------*   ``` 
    */
    'status': ListTransactions200ResponseInnerStatusEnum;
    'metadata'?: SignMetadataRequestMetadata;
    /**
    * Indicates whether the phase-2 monetary policy script (e.g. Plutus script) used in the transaction validated or not. Validity may be null if this transaction was from an era that doesn't support phase-2 monetary policy scripts, or is a pending transaction (we don't know if validation passed or failed until the transaction hits the ledger). 
    */
    'scriptValidity'?: ListTransactions200ResponseInnerScriptValidityEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "hex"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "ListTransactions200ResponseInnerAmount",
            "format": ""
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "GetUTxOsStatistics200ResponseTotal",
            "format": ""
        },
        {
            "name": "depositTaken",
            "baseName": "deposit_taken",
            "type": "GetUTxOsStatistics200ResponseTotal",
            "format": ""
        },
        {
            "name": "depositReturned",
            "baseName": "deposit_returned",
            "type": "GetUTxOsStatistics200ResponseTotal",
            "format": ""
        },
        {
            "name": "insertedAt",
            "baseName": "inserted_at",
            "type": "ListTransactions200ResponseInnerInsertedAt",
            "format": ""
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "ListTransactions200ResponseInnerExpiresAt",
            "format": ""
        },
        {
            "name": "pendingSince",
            "baseName": "pending_since",
            "type": "ListTransactions200ResponseInnerPendingSince",
            "format": ""
        },
        {
            "name": "depth",
            "baseName": "depth",
            "type": "ListTransactions200ResponseInnerDepth",
            "format": ""
        },
        {
            "name": "direction",
            "baseName": "direction",
            "type": "ListTransactions200ResponseInnerDirectionEnum",
            "format": ""
        },
        {
            "name": "inputs",
            "baseName": "inputs",
            "type": "Array<ListTransactions200ResponseInnerInputsInner>",
            "format": ""
        },
        {
            "name": "outputs",
            "baseName": "outputs",
            "type": "Array<PaymentPaymentsInner>",
            "format": ""
        },
        {
            "name": "collateral",
            "baseName": "collateral",
            "type": "Array<ListTransactions200ResponseInnerCollateralInner>",
            "format": ""
        },
        {
            "name": "collateralOutputs",
            "baseName": "collateral_outputs",
            "type": "Array<PaymentPaymentsInner>",
            "format": ""
        },
        {
            "name": "withdrawals",
            "baseName": "withdrawals",
            "type": "Array<ListTransactions200ResponseInnerWithdrawalsInner>",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ListTransactions200ResponseInnerStatusEnum",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "SignMetadataRequestMetadata",
            "format": ""
        },
        {
            "name": "scriptValidity",
            "baseName": "script_validity",
            "type": "ListTransactions200ResponseInnerScriptValidityEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListTransactions200ResponseInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ListTransactions200ResponseInnerDirectionEnum = "outgoing" | "incoming" ;
export type ListTransactions200ResponseInnerStatusEnum = "pending" | "submitted" | "in_ledger" | "expired" ;
export type ListTransactions200ResponseInnerScriptValidityEnum = "valid" | "invalid" ;

