/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The rewards the wallet can expect to receive at the end of an epoch, in the long term, if delegating to this pool.  For more details, see the [Design Specification for Delegation and Incentives in Cardano](https://hydra.iohk.io/job/Cardano/cardano-ledger-specs/delegationDesignSpec/latest/download-by-type/doc-pdf/delegation_design_spec) document. 
*/
export class ListStakePools200ResponseInnerMetricsNonMyopicMemberRewards {
    'quantity': number;
    'unit': ListStakePools200ResponseInnerMetricsNonMyopicMemberRewardsUnitEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "ListStakePools200ResponseInnerMetricsNonMyopicMemberRewardsUnitEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListStakePools200ResponseInnerMetricsNonMyopicMemberRewards.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ListStakePools200ResponseInnerMetricsNonMyopicMemberRewardsUnitEnum = "lovelace" ;

