/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MintOrBurnAssetQuantityOutOfBounds {
    /**
    * Occurs when attempting to mint or burn an asset quantity that is not greater than zero or exceeds 9223372036854775807 (2^63 - 1).
    */
    'message': string;
    'code': MintOrBurnAssetQuantityOutOfBoundsCodeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "MintOrBurnAssetQuantityOutOfBoundsCodeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MintOrBurnAssetQuantityOutOfBounds.attributeTypeMap;
    }

    public constructor() {
    }
}


export type MintOrBurnAssetQuantityOutOfBoundsCodeEnum = "mint_or_burn_asset_quantity_out_of_bounds" ;

