/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SharedWalletCannotUpdateKey } from './SharedWalletCannotUpdateKey';
import { SharedWalletKeyAlreadyExists } from './SharedWalletKeyAlreadyExists';
import { SharedWalletNoDelegationTemplate } from './SharedWalletNoDelegationTemplate';
import { SharedWalletNoSuchCosigner } from './SharedWalletNoSuchCosigner';
import { SharedWalletNotPending } from './SharedWalletNotPending';
import { HttpFile } from '../http/http';

export class PatchSharedWalletInPayment403Response {
    /**
    * Returned when a user tries to update cosigner key that contains a key of a shared wallet. Only other cosigner keys can be updated. 
    */
    'message': string;
    'code': PatchSharedWalletInPayment403ResponseCodeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "PatchSharedWalletInPayment403ResponseCodeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PatchSharedWalletInPayment403Response.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PatchSharedWalletInPayment403ResponseCodeEnum = "shared_wallet_cannot_update_key" ;

