/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentPaymentsInner } from './PaymentPaymentsInner';
import { PaymentTimeToLive } from './PaymentTimeToLive';
import { SignMetadataRequestMetadata } from './SignMetadataRequestMetadata';
import { HttpFile } from '../http/http';

export class Payment1 {
    /**
    * The wallet's master passphrase.
    */
    'passphrase': string;
    /**
    * A list of target outputs with amounts specified.
    */
    'payments': Array<PaymentPaymentsInner>;
    /**
    * When provided, instruments the server to automatically withdraw rewards from the source wallet when they are deemed sufficient (i.e. they contribute to the balance for at least as much as they cost).  As a consequence, the resulting transaction may or may not have a withdrawal object. Summarizing:  withdrawal field | reward balance | result ---              | ---            | --- `null`           | too small      | ✓ no withdrawals generated `null`           | big enough     | ✓ no withdrawals generated `\"self\"`         | too small      | ✓ no withdrawals generated `\"self\"`         | big enough     | ✓ withdrawal generated 
    */
    'withdrawal'?: Payment1WithdrawalEnum;
    'metadata'?: SignMetadataRequestMetadata;
    'timeToLive'?: PaymentTimeToLive;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "passphrase",
            "baseName": "passphrase",
            "type": "string",
            "format": ""
        },
        {
            "name": "payments",
            "baseName": "payments",
            "type": "Array<PaymentPaymentsInner>",
            "format": ""
        },
        {
            "name": "withdrawal",
            "baseName": "withdrawal",
            "type": "Payment1WithdrawalEnum",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "SignMetadataRequestMetadata",
            "format": ""
        },
        {
            "name": "timeToLive",
            "baseName": "time_to_live",
            "type": "PaymentTimeToLive",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Payment1.attributeTypeMap;
    }

    public constructor() {
    }
}


export type Payment1WithdrawalEnum = "self" ;

