/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Minimal stake amount that a stake pool is willing to honor.  May be omitted if the wallet hasn't found the pool's registration cerificate yet. 
*/
export class PoolRegistrationCertificatePoolPledge {
    'quantity': number;
    'unit': PoolRegistrationCertificatePoolPledgeUnitEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "PoolRegistrationCertificatePoolPledgeUnitEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PoolRegistrationCertificatePoolPledge.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PoolRegistrationCertificatePoolPledgeUnitEnum = "lovelace" ;

