/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Variable margin on the total reward given to an operator before splitting rewards between stakeholders.  May be omitted if the wallet hasn't found the pool's registration cerificate yet. 
*/
export class PoolRegistrationCertificatePoolMargin {
    'quantity': number;
    'unit': PoolRegistrationCertificatePoolMarginUnitEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "PoolRegistrationCertificatePoolMarginUnitEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PoolRegistrationCertificatePoolMargin.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PoolRegistrationCertificatePoolMarginUnitEnum = "percent" ;

