/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PoolRegistrationCertificatePoolCost } from './PoolRegistrationCertificatePoolCost';
import { PoolRegistrationCertificatePoolMargin } from './PoolRegistrationCertificatePoolMargin';
import { PoolRegistrationCertificatePoolMetadata } from './PoolRegistrationCertificatePoolMetadata';
import { PoolRegistrationCertificatePoolPledge } from './PoolRegistrationCertificatePoolPledge';
import { HttpFile } from '../http/http';

export class PoolRegistrationCertificate {
    'certificateType': PoolRegistrationCertificateCertificateTypeEnum;
    /**
    * A unique identifier for the pool.
    */
    'poolId': string;
    'poolOwners': Array<string>;
    'poolMargin': PoolRegistrationCertificatePoolMargin;
    'poolCost': PoolRegistrationCertificatePoolCost;
    'poolPledge': PoolRegistrationCertificatePoolPledge;
    'poolMetadata'?: PoolRegistrationCertificatePoolMetadata;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "certificateType",
            "baseName": "certificate_type",
            "type": "PoolRegistrationCertificateCertificateTypeEnum",
            "format": ""
        },
        {
            "name": "poolId",
            "baseName": "pool_id",
            "type": "string",
            "format": "hex|bech32"
        },
        {
            "name": "poolOwners",
            "baseName": "pool_owners",
            "type": "Array<string>",
            "format": "bech32"
        },
        {
            "name": "poolMargin",
            "baseName": "pool_margin",
            "type": "PoolRegistrationCertificatePoolMargin",
            "format": ""
        },
        {
            "name": "poolCost",
            "baseName": "pool_cost",
            "type": "PoolRegistrationCertificatePoolCost",
            "format": ""
        },
        {
            "name": "poolPledge",
            "baseName": "pool_pledge",
            "type": "PoolRegistrationCertificatePoolPledge",
            "format": ""
        },
        {
            "name": "poolMetadata",
            "baseName": "pool_metadata",
            "type": "PoolRegistrationCertificatePoolMetadata",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PoolRegistrationCertificate.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PoolRegistrationCertificateCertificateTypeEnum = "register_pool" ;

