/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Estimated cost set by the pool operator when registering his pool. This fixed cost is taken from each reward earned by the pool before splitting rewards between stakeholders.  May be omitted if the wallet hasn't found the pool's registration cerificate yet. 
*/
export class PoolRegistrationCertificatePoolCost {
    'quantity': number;
    'unit': PoolRegistrationCertificatePoolCostUnitEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "PoolRegistrationCertificatePoolCostUnitEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PoolRegistrationCertificatePoolCost.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PoolRegistrationCertificatePoolCostUnitEnum = "lovelace" ;

