/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AlreadyWithdrawing } from './AlreadyWithdrawing';
import { CannotCoverFee } from './CannotCoverFee';
import { InputsDepleted } from './InputsDepleted';
import { InsufficientCollateral } from './InsufficientCollateral';
import { InvalidCoinSelection } from './InvalidCoinSelection';
import { InvalidWalletType } from './InvalidWalletType';
import { NotEnoughMoney } from './NotEnoughMoney';
import { OutputTokenBundleSizeExceedsLimit } from './OutputTokenBundleSizeExceedsLimit';
import { OutputTokenQuantityExceedsLimit } from './OutputTokenQuantityExceedsLimit';
import { TransactionIsTooBig } from './TransactionIsTooBig';
import { UtxoTooSmall } from './UtxoTooSmall';
import { HttpFile } from '../http/http';

export class PostTransactionFee403Response {
    /**
    * May occur when the wallet can't cover for all requested outputs without making the transaction too large.
    */
    'message': string;
    'code': PostTransactionFee403ResponseCodeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "PostTransactionFee403ResponseCodeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PostTransactionFee403Response.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PostTransactionFee403ResponseCodeEnum = "transaction_is_too_big" ;

