/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The maintenance action to carry out, current values are   - gc_stake_pools -> trigger looking up delisted pools from the remote SMASH server 
*/
export class PostMaintenanceActionRequest {
    'maintenanceAction': PostMaintenanceActionRequestMaintenanceActionEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "maintenanceAction",
            "baseName": "maintenance_action",
            "type": "PostMaintenanceActionRequestMaintenanceActionEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PostMaintenanceActionRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PostMaintenanceActionRequestMaintenanceActionEnum = "gc_stake_pools" ;

