/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SharedWalletScriptTemplateInvalid } from './SharedWalletScriptTemplateInvalid';
import { HttpFile } from '../http/http';

export class PostSharedWallet403Response {
    /**
    * Returned when a user tries to create a shared wallet with script template that does not pass validation. 
    */
    'message': string;
    'code': PostSharedWallet403ResponseCodeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "PostSharedWallet403ResponseCodeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PostSharedWallet403Response.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PostSharedWallet403ResponseCodeEnum = "shared_wallet_script_template_invalid" ;

