/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreatedWrongPolicyScriptTemplate } from './CreatedWrongPolicyScriptTemplate';
import { InvalidWalletType } from './InvalidWalletType';
import { MissingPolicyPublicKey } from './MissingPolicyPublicKey';
import { HttpFile } from '../http/http';

export class PostPolicyId403Response {
    /**
    * Occurs when a policy script template either does not pass validation or has more than one cosigner.
    */
    'message': string;
    'code': PostPolicyId403ResponseCodeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "PostPolicyId403ResponseCodeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PostPolicyId403Response.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PostPolicyId403ResponseCodeEnum = "created_wrong_policy_script_template" ;

