/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PostAccountKeySharedRequest {
    /**
    * A master passphrase to lock and protect the wallet for sensitive operation (e.g. sending funds)
    */
    'passphrase': string;
    /**
    * Determines whether extended (with chain code) or normal (without chain code) key is requested
    */
    'format': PostAccountKeySharedRequestFormatEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "passphrase",
            "baseName": "passphrase",
            "type": "string",
            "format": ""
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "PostAccountKeySharedRequestFormatEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PostAccountKeySharedRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PostAccountKeySharedRequestFormatEnum = "extended" | "non_extended" ;

