/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A transaction input not belonging to a given wallet. 
*/
export class TxInputsWithoutSourceNotBelongingToAGivenWallet {
    /**
    * A unique identifier for this transaction
    */
    'id': string;
    'index': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "hex"
        },
        {
            "name": "index",
            "baseName": "index",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TxInputsWithoutSourceNotBelongingToAGivenWallet.attributeTypeMap;
    }

    public constructor() {
    }
}

