/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: v2022-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class WalletAlreadyExists {
    /**
    * May occur when a otherwise valid request would yield a wallet that already exists.
    */
    'message': string;
    'code': WalletAlreadyExistsCodeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "WalletAlreadyExistsCodeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WalletAlreadyExists.attributeTypeMap;
    }

    public constructor() {
    }
}


export type WalletAlreadyExistsCodeEnum = "wallet_already_exists" ;

